name: Build and deploy Node.js app to Azure WebApp - webappback

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
      working-directory: webapp-backend
        run: npm install

      # Si no tienes script de build, quita este paso
      # - name: Build project
      #   run: npm run build

      - name: Zip artifact for deployment
        run: cd webapp-backend && zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          auth-type: federated

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: webappback # Asegúrate que el nombre coincide EXACTAMENTE con el de Azure
          package: './release.zip'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
